/* Generated by scripts/vendor-minimal-react-template.cjs — template: minimal-react */
const path = require('path')
const { createMinimalReactWebviewWebpackConfig } = require('./bundler/webpack.factory.js')

const context = path.resolve(__dirname, '..')
const templateRoot = path.resolve(__dirname, 'bundler')

module.exports = createMinimalReactWebviewWebpackConfig({
  context,
  entry: path.resolve(context, 'src/webview/index.tsx'),
  htmlTemplate: path.resolve(templateRoot, 'src/index.html'),
  favicon: path.resolve(templateRoot, 'src/favicon.ico'),
  babelConfig: path.resolve(context, '.babelrc')
})
